import { PurchaseItem, ClaimRecord, DashboardStats } from '../types';

export const INITIAL_STATS: DashboardStats = {
  totalPurchases: 12,
  expiringSoon: 3,
  activeWarranties: 8,
  totalSpend: 84920,
};

export const MOCK_PURCHASES: PurchaseItem[] = [
  {
    id: 'sony-wh-ch720n',
    productName: 'Sony WH-CH720N',
    category: 'Audio',
    seller: 'Amazon',
    orderId: 'OD-402-8921890-4491021',
    purchaseDate: '12 Sep 2026',
    purchasePrice: 4999,
    currency: '₹',
    paymentMethod: 'HDFC Bank Millennia Credit Card (••4092)',
    invoice: {
      fileName: 'Invoice_Amazon_Sony_WHCH720N.pdf',
      fileSize: '412 KB',
      fileType: 'PDF',
      uploadDate: '12 Sep 2026',
      invoiceNumber: 'INV-BLR-2026-90412',
      taxGst: '29AABCS1429B1ZB',
    },
    returnWindow: {
      policyDays: 7,
      purchaseDate: '12 Sep 2026',
      deadlineDate: '19 Sep 2026',
      daysRemaining: 1,
      isExpired: false,
      statusText: '1 day left (Expires tomorrow)',
      urgency: 'critical',
    },
    warranty: {
      provider: 'Sony India Authorized Service',
      coveragePeriod: '2 Years Manufacturer',
      durationMonths: 24,
      startDate: '12 Sep 2026',
      expiryDate: '11 Sep 2028',
      daysRemaining: 722,
      monthsRemaining: 24,
      statusText: '24 months remaining',
      isValid: true,
      urgency: 'active',
      coverageDetails: [
        'Full hardware replacement for acoustic drivers',
        'ANC module & circuit board failure coverage',
        'Complimentary pickup & drop at Sony Centers across India',
      ],
      claimHotline: '1800-103-7799',
      serialNumber: 'S01-9482910-B',
    },
    claimStatus: 'ready',
    claimPack: {
      claimId: 'CLM-SONY-720',
      status: 'ready',
      notes: 'Purchase invoice and warranty validation certificate generated.',
    },
    notes: 'Bought during Great Indian Festival preview sale.',
  },
  {
    id: 'samsung-galaxy-m55',
    productName: 'Samsung Galaxy M55',
    category: 'Smartphones',
    seller: 'Flipkart',
    orderId: 'FK-OD-892100412891',
    purchaseDate: '14 Sep 2026',
    purchasePrice: 24999,
    currency: '₹',
    paymentMethod: 'UPI (Axis Bank / tanyagarg@okaxis)',
    invoice: {
      fileName: 'Tax_Invoice_Flipkart_Samsung_M55.pdf',
      fileSize: '620 KB',
      fileType: 'PDF',
      uploadDate: '14 Sep 2026',
      invoiceNumber: 'FK-MUM-2026-88102',
      taxGst: '27AAECF5521M1Z5',
    },
    returnWindow: {
      policyDays: 7,
      purchaseDate: '14 Sep 2026',
      deadlineDate: '21 Sep 2026',
      daysRemaining: 3,
      isExpired: false,
      statusText: '3 days left',
      urgency: 'warning',
    },
    warranty: {
      provider: 'Samsung Care+',
      coveragePeriod: '1 Year Comprehensive',
      durationMonths: 12,
      startDate: '14 Sep 2026',
      expiryDate: '11 Oct 2026',
      daysRemaining: 21,
      monthsRemaining: 1,
      statusText: '21 days remaining',
      isValid: true,
      urgency: 'expiring_soon',
      coverageDetails: [
        'AMOLED Display manufacturing defects',
        'Motherboard & processor thermal malfunction',
        'Original charger & battery replacement within warranty',
      ],
      claimHotline: '1800-407-267864',
      serialNumber: 'SM-M556B-883019',
    },
    claimStatus: 'none',
    notes: 'Includes 45W super fast charger bundled in Flipkart festive combo.',
  },
  {
    id: 'logitech-mx-master-3s',
    productName: 'Logitech MX Master 3S',
    category: 'Computing',
    seller: 'Amazon',
    orderId: 'OD-501-1928341-9921204',
    purchaseDate: '22 Aug 2026',
    purchasePrice: 7495,
    currency: '₹',
    paymentMethod: 'ICICI Amazon Pay Credit Card (••1180)',
    invoice: {
      fileName: 'Invoice_Amazon_Logitech_MXMaster3S.pdf',
      fileSize: '348 KB',
      fileType: 'PDF',
      uploadDate: '22 Aug 2026',
      invoiceNumber: 'INV-DEL-2026-77192',
      taxGst: '07AAACL1948Q1ZL',
    },
    returnWindow: {
      policyDays: 10,
      purchaseDate: '22 Aug 2026',
      deadlineDate: '01 Sep 2026',
      daysRemaining: 0,
      isExpired: true,
      statusText: 'Expired',
      urgency: 'expired',
    },
    warranty: {
      provider: 'Logitech India Support',
      coveragePeriod: '1 Year Limited Hardware',
      durationMonths: 12,
      startDate: '22 Aug 2026',
      expiryDate: '21 Aug 2027',
      daysRemaining: 335,
      monthsRemaining: 11,
      statusText: '11 months remaining',
      isValid: true,
      urgency: 'active',
      coverageDetails: [
        'MagSpeed electromagnetic scroll wheel mechanism',
        'Darkfield 8000 DPI sensor precision guarantee',
        'Direct replacement unit if left click switch fails',
      ],
      claimHotline: '000-800-440-2450',
      serialNumber: 'LZ-92014-MX3S',
    },
    claimStatus: 'ready',
    claimPack: {
      claimId: 'CLM-LOGI-3S',
      status: 'ready',
      notes: 'Warranty claim information is available and ready for submission.',
    },
    notes: 'Registered with Logitech G Hub / Options+.',
  },
  {
    id: 'apple-airpods',
    productName: 'Apple AirPods',
    category: 'Audio',
    seller: 'Apple',
    orderId: 'W1092841029',
    purchaseDate: '05 Jul 2026',
    purchasePrice: 14900,
    currency: '₹',
    paymentMethod: 'Apple Pay / HDFC Bank Debit Card (••3319)',
    invoice: {
      fileName: 'Apple_Store_BKC_Tax_Invoice.pdf',
      fileSize: '512 KB',
      fileType: 'PDF',
      uploadDate: '05 Jul 2026',
      invoiceNumber: 'APL-BKC-2026-0912',
      taxGst: '27AABCA1298P1ZX',
    },
    returnWindow: {
      policyDays: 14,
      purchaseDate: '05 Jul 2026',
      deadlineDate: '19 Jul 2026',
      daysRemaining: 0,
      isExpired: true,
      statusText: 'Expired',
      urgency: 'expired',
    },
    warranty: {
      provider: 'AppleCare Standard Warranty',
      coveragePeriod: '1 Year Limited',
      durationMonths: 12,
      startDate: '05 Jul 2026',
      expiryDate: '04 Jul 2027',
      daysRemaining: 287,
      monthsRemaining: 9,
      statusText: '9 months remaining',
      isValid: true,
      urgency: 'active',
      coverageDetails: [
        'Apple Genuine battery health guarantee (<80% capacity)',
        'H1/H2 chip Bluetooth synchronization failure',
        'Worldwide service at any authorized Apple Store or Genius Bar',
      ],
      claimHotline: '000800-100-9009',
      serialNumber: 'GW09KL8P12',
    },
    claimStatus: 'none',
    notes: 'Bought at Apple BKC Mumbai store.',
  },
  {
    id: 'kindle-paperwhite',
    productName: 'Kindle Paperwhite (16 GB)',
    category: 'Computing',
    seller: 'Amazon',
    orderId: 'OD-302-8812901-4401298',
    purchaseDate: '15 Jun 2026',
    purchasePrice: 10999,
    currency: '₹',
    paymentMethod: 'Amazon Pay UPI',
    invoice: {
      fileName: 'Amazon_Kindle_Paperwhite_Tax_Inv.pdf',
      fileSize: '390 KB',
      fileType: 'PDF',
      uploadDate: '15 Jun 2026',
      invoiceNumber: 'INV-HYD-2026-44102',
      taxGst: '36AAACE1192L1ZO',
    },
    returnWindow: {
      policyDays: 10,
      purchaseDate: '15 Jun 2026',
      deadlineDate: '25 Jun 2026',
      daysRemaining: 0,
      isExpired: true,
      statusText: 'Expired',
      urgency: 'expired',
    },
    warranty: {
      provider: 'Amazon Device Support',
      coveragePeriod: '1 Year Limited',
      durationMonths: 12,
      startDate: '15 Jun 2026',
      expiryDate: '14 Jun 2027',
      daysRemaining: 267,
      monthsRemaining: 9,
      statusText: '9 months remaining',
      isValid: true,
      urgency: 'active',
      coverageDetails: [
        'E-ink flush-front display dead pixels or uneven backlight',
        'IPX8 waterproof seal integrity',
      ],
      claimHotline: '1800-3000-9009',
      serialNumber: 'G001LG09128001P',
    },
    claimStatus: 'none',
  },
  {
    id: 'boat-nirvana-ion',
    productName: 'boAt Nirvana Ion TWS',
    category: 'Audio',
    seller: 'Flipkart',
    orderId: 'FK-OD-9011928014',
    purchaseDate: '18 Sep 2026',
    purchasePrice: 1999,
    currency: '₹',
    paymentMethod: 'Paytm UPI',
    invoice: {
      fileName: 'Flipkart_Boat_Nirvana_Ion.pdf',
      fileSize: '290 KB',
      fileType: 'PDF',
      uploadDate: '18 Sep 2026',
      invoiceNumber: 'FK-BLR-2026-40191',
      taxGst: '29AABCF1029P1ZA',
    },
    returnWindow: {
      policyDays: 7,
      purchaseDate: '18 Sep 2026',
      deadlineDate: '25 Sep 2026',
      daysRemaining: 5,
      isExpired: false,
      statusText: '5 days left',
      urgency: 'normal',
    },
    warranty: {
      provider: 'Imagine Marketing (boAt Care)',
      coveragePeriod: '1 Year Replacement',
      durationMonths: 12,
      startDate: '18 Sep 2026',
      expiryDate: '17 Sep 2027',
      daysRemaining: 362,
      monthsRemaining: 12,
      statusText: '12 months remaining',
      isValid: true,
      urgency: 'active',
      coverageDetails: [
        'Doorstep pickup and doorstep replacement across 15,000 pin codes',
        'Driver imbalance or charging dock defect',
      ],
      claimHotline: '022-6918-1920',
      serialNumber: 'BT-ION-881928',
    },
    claimStatus: 'none',
  },
  {
    id: 'mi-smart-air-fryer',
    productName: 'Xiaomi Smart Air Fryer 3.5L',
    category: 'Home Appliances',
    seller: 'Mi Store',
    orderId: 'MI-IN-2026-09182',
    purchaseDate: '10 Jan 2026',
    purchasePrice: 6499,
    currency: '₹',
    paymentMethod: 'SBI Net Banking',
    invoice: {
      fileName: 'Xiaomi_Store_AirFryer_Invoice.pdf',
      fileSize: '480 KB',
      fileType: 'PDF',
      uploadDate: '10 Jan 2026',
      invoiceNumber: 'MI-BLR-2026-10291',
    },
    returnWindow: {
      policyDays: 14,
      purchaseDate: '10 Jan 2026',
      deadlineDate: '24 Jan 2026',
      daysRemaining: 0,
      isExpired: true,
      statusText: 'Expired',
      urgency: 'expired',
    },
    warranty: {
      provider: 'Xiaomi India Service',
      coveragePeriod: '1 Year On-site',
      durationMonths: 12,
      startDate: '10 Jan 2026',
      expiryDate: '09 Jan 2027',
      daysRemaining: 111,
      monthsRemaining: 3,
      statusText: '3 months remaining',
      isValid: true,
      urgency: 'active',
      coverageDetails: [
        'Heating element and internal fan motor breakdown',
        'OLED rotary control knob functionality',
      ],
      claimHotline: '1800-103-6286',
      serialNumber: 'MAF02-9901428',
    },
    claimStatus: 'none',
  },
  {
    id: 'sandisk-extreme-ssd',
    productName: 'SanDisk Extreme Portable SSD 1TB',
    category: 'Computing',
    seller: 'Amazon',
    orderId: 'OD-110-8910291-8891024',
    purchaseDate: '28 Aug 2026',
    purchasePrice: 5490,
    currency: '₹',
    paymentMethod: 'Amazon Pay Balance',
    invoice: {
      fileName: 'SanDisk_1TB_Amazon_TaxInvoice.pdf',
      fileSize: '360 KB',
      fileType: 'PDF',
      uploadDate: '28 Aug 2026',
      invoiceNumber: 'INV-BOM-2026-99120',
    },
    returnWindow: {
      policyDays: 7,
      purchaseDate: '28 Aug 2026',
      deadlineDate: '04 Sep 2026',
      daysRemaining: 0,
      isExpired: true,
      statusText: 'Expired',
      urgency: 'expired',
    },
    warranty: {
      provider: 'Western Digital India',
      coveragePeriod: '5 Years Limited Warranty',
      durationMonths: 60,
      startDate: '28 Aug 2026',
      expiryDate: '27 Aug 2031',
      daysRemaining: 1802,
      monthsRemaining: 59,
      statusText: '59 months remaining',
      isValid: true,
      urgency: 'active',
      coverageDetails: [
        'End-to-end NAND flash data controller failure replacement',
        'IP55 dust and water resistance seal warranty',
      ],
      claimHotline: '1800-102-2055',
      serialNumber: 'SD-EXT-1TB-2026X',
    },
    claimStatus: 'none',
  },
  {
    id: 'portronics-gan-charger',
    productName: 'Portronics Adapto 65W GaN Charger',
    category: 'Accessories',
    seller: 'Amazon',
    orderId: 'OD-702-8819201-1192801',
    purchaseDate: '02 Sep 2026',
    purchasePrice: 1499,
    currency: '₹',
    paymentMethod: 'Google Pay (UPI)',
    invoice: {
      fileName: 'Portronics_65W_Invoice.pdf',
      fileSize: '275 KB',
      fileType: 'PDF',
      uploadDate: '02 Sep 2026',
      invoiceNumber: 'INV-BLR-2026-29188',
    },
    returnWindow: {
      policyDays: 7,
      purchaseDate: '02 Sep 2026',
      deadlineDate: '09 Sep 2026',
      daysRemaining: 0,
      isExpired: true,
      statusText: 'Expired',
      urgency: 'expired',
    },
    warranty: {
      provider: 'Portronics Support',
      coveragePeriod: '6 Months',
      durationMonths: 6,
      startDate: '02 Sep 2026',
      expiryDate: '01 Mar 2027',
      daysRemaining: 162,
      monthsRemaining: 5,
      statusText: '5 months remaining',
      isValid: true,
      urgency: 'active',
      coverageDetails: ['Short circuit protection & GaN chip malfunction'],
      serialNumber: 'PT-ADAP65-901',
    },
    claimStatus: 'none',
  },
  {
    id: 'noise-colorfit-pro5',
    productName: 'Noise ColorFit Pro 5 Smartwatch',
    category: 'Wearables',
    seller: 'Croma',
    orderId: 'CR-ON-8891024-991',
    purchaseDate: '14 Feb 2026',
    purchasePrice: 2790,
    currency: '₹',
    paymentMethod: 'Tata Neu UPI',
    invoice: {
      fileName: 'Croma_Invoice_Noise_ColorFit_Pro5.pdf',
      fileSize: '510 KB',
      fileType: 'PDF',
      uploadDate: '14 Feb 2026',
      invoiceNumber: 'CRO-MUM-2026-7721',
    },
    returnWindow: {
      policyDays: 7,
      purchaseDate: '14 Feb 2026',
      deadlineDate: '21 Feb 2026',
      daysRemaining: 0,
      isExpired: true,
      statusText: 'Expired',
      urgency: 'expired',
    },
    warranty: {
      provider: 'Noise Nexxbase Support',
      coveragePeriod: '1 Year Limited',
      durationMonths: 12,
      startDate: '14 Feb 2026',
      expiryDate: '13 Feb 2027',
      daysRemaining: 146,
      monthsRemaining: 5,
      statusText: '5 months remaining',
      isValid: true,
      urgency: 'active',
      coverageDetails: ['Optical heart rate sensor & touch digitizer repair'],
      serialNumber: 'NCF-P5-110294',
    },
    claimStatus: 'none',
  },
  {
    id: 'echo-dot-5th-gen',
    productName: 'Amazon Echo Dot (5th Gen) with Clock',
    category: 'Home Appliances',
    seller: 'Amazon',
    orderId: 'OD-201-9928102-3341902',
    purchaseDate: '18 Nov 2025',
    purchasePrice: 2990,
    currency: '₹',
    paymentMethod: 'Amazon Pay ICICI Card',
    invoice: {
      fileName: 'Echo_Dot_Amazon_Bill.pdf',
      fileSize: '310 KB',
      fileType: 'PDF',
      uploadDate: '18 Nov 2025',
      invoiceNumber: 'INV-HYD-2025-10291',
    },
    returnWindow: {
      policyDays: 10,
      purchaseDate: '18 Nov 2025',
      deadlineDate: '28 Nov 2025',
      daysRemaining: 0,
      isExpired: true,
      statusText: 'Expired',
      urgency: 'expired',
    },
    warranty: {
      provider: 'Amazon Device Warranty',
      coveragePeriod: '1 Year',
      durationMonths: 12,
      startDate: '18 Nov 2025',
      expiryDate: '17 Nov 2026',
      daysRemaining: 58,
      monthsRemaining: 2,
      statusText: '2 months remaining',
      isValid: true,
      urgency: 'active',
      coverageDetails: ['Speaker driver, mic array, and LED display clock array'],
      serialNumber: 'G091LK18290123',
    },
    claimStatus: 'none',
  },
  {
    id: 'anker-powerline-cable',
    productName: 'Anker Powerline+ III USB-C to Lightning (6ft)',
    category: 'Accessories',
    seller: 'Amazon',
    orderId: 'OD-991-0029182-4412981',
    purchaseDate: '10 Aug 2025',
    purchasePrice: 1250,
    currency: '₹',
    paymentMethod: 'UPI',
    invoice: {
      fileName: 'Anker_Cable_Tax_Invoice.pdf',
      fileSize: '210 KB',
      fileType: 'PDF',
      uploadDate: '10 Aug 2025',
      invoiceNumber: 'INV-DEL-2025-44910',
    },
    returnWindow: {
      policyDays: 7,
      purchaseDate: '10 Aug 2025',
      deadlineDate: '17 Aug 2025',
      daysRemaining: 0,
      isExpired: true,
      statusText: 'Expired',
      urgency: 'expired',
    },
    warranty: {
      provider: 'Anker Innovations India',
      coveragePeriod: '1 Year Hassle-Free',
      durationMonths: 12,
      startDate: '10 Aug 2025',
      expiryDate: '09 Aug 2026',
      daysRemaining: 0,
      monthsRemaining: 0,
      statusText: 'Expired',
      isValid: false,
      urgency: 'expired',
      coverageDetails: ['Lifetime strain relief cable bend warranty'],
      serialNumber: 'ANK-PL3-99120',
    },
    claimStatus: 'none',
  },
];

export const MOCK_CLAIMS: ClaimRecord[] = [
  {
    id: 'CLM-2026-001',
    purchaseId: 'sony-wh-ch720n',
    productName: 'Sony WH-CH720N',
    seller: 'Amazon',
    purchaseDate: '12 Sep 2026',
    claimDate: '19 Sep 2026',
    status: 'ready',
    issueDescription: 'Left ear cup active noise cancellation crackle during high volume.',
    warrantyProvider: 'Sony India Authorized Service',
  },
  {
    id: 'CLM-2026-002',
    purchaseId: 'samsung-galaxy-m55',
    productName: 'Samsung Galaxy M55',
    seller: 'Flipkart',
    purchaseDate: '14 Sep 2026',
    claimDate: '18 Sep 2026',
    status: 'in_progress',
    issueDescription: 'Fast charging negotiation dropping intermittently to standard 10W.',
    ticketNumber: 'SAM-CARE-991280-IN',
    warrantyProvider: 'Samsung Care+',
  },
  {
    id: 'CLM-2026-003',
    purchaseId: 'logitech-mx-master-3s',
    productName: 'Logitech MX Master 3S',
    seller: 'Amazon',
    purchaseDate: '22 Aug 2026',
    claimDate: '10 Sep 2026',
    status: 'completed',
    issueDescription: 'Gesture thumb button stuck down; free brand-new replacement dispatched.',
    ticketNumber: 'LOGI-TKT-441209',
    resolution: 'New replacement mouse delivered by courier with updated invoice.',
    amountCovered: 7495,
    warrantyProvider: 'Logitech India Support',
  },
];

export const ASK_BILLBACK_SUGGESTIONS = [
  'Which products are still under warranty?',
  'What returns expire this week?',
  'How much did I spend on electronics?',
  'Show purchases from September.',
];

export const ASK_BILLBACK_RESPONSES: Record<string, { answer: string; items: { name: string; detail: string; statusType: 'green' | 'amber' | 'blue' }[]; countNote: string }> = {
  'Which products are still under warranty?': {
    answer: 'You have 8 products with active warranties in your vault.',
    items: [
      { name: 'Sony WH-CH720N', detail: '24 months remaining', statusType: 'green' },
      { name: 'Samsung Galaxy M55', detail: '21 days remaining', statusType: 'amber' },
      { name: 'Logitech MX Master 3S', detail: '11 months remaining', statusType: 'green' },
      { name: 'Apple AirPods', detail: '9 months remaining', statusType: 'green' },
      { name: 'SanDisk Extreme 1TB SSD', detail: '59 months remaining', statusType: 'green' },
    ],
    countNote: 'Based on 12 saved purchases',
  },
  'What returns expire this week?': {
    answer: 'You have 3 return deadlines expiring over the next 7 days.',
    items: [
      { name: 'Sony WH-CH720N', detail: 'Expires tomorrow (1 day left)', statusType: 'amber' },
      { name: 'Samsung Galaxy M55', detail: 'Expires in 3 days', statusType: 'amber' },
      { name: 'boAt Nirvana Ion TWS', detail: 'Expires in 5 days', statusType: 'blue' },
    ],
    countNote: 'Amazon and Flipkart 7-day replacement windows',
  },
  'How much did I spend on electronics?': {
    answer: 'You have spent ₹84,920 across 12 tracked electronics and gadget purchases.',
    items: [
      { name: 'Smartphones (Galaxy M55)', detail: '₹24,999 (29.4%)', statusType: 'blue' },
      { name: 'Audio (Sony, AirPods, boAt)', detail: '₹21,898 (25.8%)', statusType: 'blue' },
      { name: 'Computing & Storage (Logitech, Kindle, SanDisk)', detail: '₹23,984 (28.2%)', statusType: 'blue' },
      { name: 'Home & Accessories (Air Fryer, Echo, GaN Charger)', detail: '₹14,039 (16.5%)', statusType: 'blue' },
    ],
    countNote: 'Aggregated from 12 verified invoices',
  },
  'Show purchases from September.': {
    answer: 'You have 4 registered purchases from September 2026.',
    items: [
      { name: 'boAt Nirvana Ion TWS', detail: '18 Sep 2026 — ₹1,999 (Flipkart)', statusType: 'blue' },
      { name: 'Samsung Galaxy M55', detail: '14 Sep 2026 — ₹24,999 (Flipkart)', statusType: 'blue' },
      { name: 'Sony WH-CH720N', detail: '12 Sep 2026 — ₹4,999 (Amazon)', statusType: 'blue' },
      { name: 'Portronics 65W GaN Charger', detail: '02 Sep 2026 — ₹1,499 (Amazon)', statusType: 'blue' },
    ],
    countNote: 'Total September spend: ₹33,496',
  },
};
